version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ls -ltrh
      - aws cloudformation validate-template --template-body file://ec2cft.yml
      #- aws cloudformation create-stack --stack-name codebuildec2stack --template-body file://ec2cft.yml
      #- aws codepipeline start-pipeline-execution --name codepipelinecft
      # - aws cloudformation create-stack --stack-name codebuildemrstack --template-body file://EMR.yml --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
      # - aws codebuild start-build --project-name cftcodebuild
      # - aws s3 ls
      # - aws s3 sync . s3://codebuildpipelinecftbucket
      - zip -r bootstrapfile.txt.zip bootstrapfile.txt
      - aws s3 cp bootstrapfile.txt.zip s3://"cf-templates-z4l0q3hmcyj4-us-east-1"
      
  post_build:
    commands:
      - echo Build completed on `date`
      # - aws cloudformation delete-stack --stack-name codebuildec2stack

artifacts:
  files:
    - '**/*'
